### ISSUE TITLE
Transition Performance in Collapsible mode

### ISSUE THREAD

**Issue by mojtabashabani** [expandjs/mat-list#2]
there is Performance problem in android webview or in chrome for android for transition in collapsible mode

**Comment by Pupix** [comment]
Could you elaborate?

Are you testing the demos provided by http://expandjs.com or did you build a `mat-list` of your own?

**Comment by Pupix** [comment]
The performance issues have been solved.

If you are using a `mat-list` with collapsible `mat-sublist` the list must have a fixed height, either by directly setting `height` or applying a `fit layout` in the form of `position: absolute; top: 0; right: 0; bottom: 0; left: 0;`.

You can check out the demo [here](http://expandjs.com/demo/mat-list) or interact with the navigation drawer from the left.
